#############################################################################
# Makefile for building: avshop
# Generated by qmake (2.01a) (Qt 4.6.1) on: Thu Feb 4 13:23:17 2010
# Project:  avshop.pro
# Template: app
# Command: /opt/qtsdk-2010.01/qt/bin/qmake -spec /opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile avshop.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2010.01/qt/include/QtCore -I/opt/qtsdk-2010.01/qt/include/QtGui -I/opt/qtsdk-2010.01/qt/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2010.01/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2010.01/qt/lib -lQtGui -L/opt/qtsdk-2010.01/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2010.01/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =  
OBJECTS       = 
DIST          = /opt/qtsdk-2010.01/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/include_source_dir.prf \
		avshop.pro
QMAKE_TARGET  = avshop
DESTDIR       = 
TARGET        = avshop

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: avshop.pro  /opt/qtsdk-2010.01/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2010.01/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.01/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/warn_on.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.01/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2010.01/qt/lib/libQtGui.prl \
		/opt/qtsdk-2010.01/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile avshop.pro
/opt/qtsdk-2010.01/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2010.01/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2010.01/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2010.01/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2010.01/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/warn_on.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2010.01/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2010.01/qt/lib/libQtGui.prl:
/opt/qtsdk-2010.01/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2010.01/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile avshop.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/avshop1.0.0 || $(MKDIR) .tmp/avshop1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/avshop1.0.0/ && (cd `dirname .tmp/avshop1.0.0` && $(TAR) avshop1.0.0.tar avshop1.0.0 && $(COMPRESS) avshop1.0.0.tar) && $(MOVE) `dirname .tmp/avshop1.0.0`/avshop1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/avshop1.0.0


clean:compiler_clean 
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

